baseURL = "https://zackaz.work"
languageCode = "zh-TW"
summaryLength = "10"
theme = "kross-hugo"
title = "Futurgata 未來氏型"
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[params]
address = ""
author = "Zackaz Kuo"
copyright = "Copyright &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"
description = "您好，很高興來到我的網站，我是一個UI/UX Designer，偶爾畫些插畫，希望您會喜歡我的作品。"
email = "zackaz@futurgata.com"
google_analytics_id = "UA-167211425-1"
home = "郭書銘 | 網站履歷"
logo = "images/logo_20201616_dark.png"
phone = "0910668696"
social = []
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
